### ISSUE TITLE
商品出品画面について

### ISSUE THREAD

**Issue by komstyle** [komstyle/freemarket_sample_68d#51]
# What
①商品出品画面で画像を添付して保存しても、
データベースに#<ActionDispatch::Http::UploadedFile:0x00007fde404f9900>
というように保存されてしまう。

②商品出品フォームにブランドの入力フォームがない。

**Comment by yuta-enomoto** [comment]
item_imagesモデルの
```mount_uploader :url, ImageUploader```
の部分をコメントアウトしているため#ActionDispatch::Http::UploadedFile:0x00007fde404f9900と保存されるのだと思います。　
ただそこの記述があるとseedで画像が入らないので一旦コメントアウトしておきました:おじぎ_男性: 犯人は僕です。

**Comment by yuta-enomoto** [comment]
いつかの話し合いから、ブランドは実装しないものだと思っていました。。
すぐに実装可能なので明日にブランドも付け足してテストまでしておきます！！

**Comment by komstyle** [comment]
確認不足でした！コメントアウト外したら保存できました！
ブランドは時間があるときでいいので、お願いします！
