### ISSUE TITLE
【依頼】最終課題挙動確認

### ISSUE THREAD

**Issue by komstyle** [komstyle/freemarket_sample_68d#69]
■ URL
IPアドレス：http://18.178.190.221/
Github（最終課題のリポジトリ）：freemarket_sample_68d

■ Basic認証
ID：admin
Pass：2222

■ テスト用アカウント
◯ 購入者用
メールアドレス：aaa@a.a
パスワード：q111111

◯ 購入用カード情報
番号：4012888888881881
期限：7/23
セキュリティカード：123

◯ 出品者用
メールアドレス:kkk@k.k
パスワード：q111111

**Comment by miyu-yamamoto** [comment]
提出ありがとうございます！
確認させて頂いたところ、必須機能については問題ありませんでしたが、以下の不備が見受けられましたので修正をお願いします！

**○出品した商品を編集するとカテゴリがリセットされてしまう**
　→メンズで登録していてもデフォルトで入力されているレディースに変更され、そのまま登録される 
**○ 出品されている商品が一覧に表示されない**
**○ ログアウト状態でも商品詳細ページを見ることができない**
　→商品詳細ページに移管でず、ログイン画面になります
**○ 出品されている商品のページから購入をクリックするとエラー画面になる**
　(あとから該当の商品を見るとSold outに変わっているため購入はできているようです)
[![Image from Gyazo](https://i.gyazo.com/fe2e6fa99a6c5109646daf2d15f5ab01.png)](https://gyazo.com/fe2e6fa99a6c5109646daf2d15f5ab01)

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfMuna4xX0zQ6_L8vRFrevse1I8VkCcdMp-24egzeH_JmIllg/viewform

**Comment by komstyle** [comment]
○出品した商品を編集するとカテゴリがリセットされてしまう
　→デフォルト値を既に入力されているデータに修正しました。
○ 出品されている商品が一覧に表示されない
　→カテゴリやブランドに関係なく、新着商品が表示される項目を追加しました。
○ ログアウト状態でも商品詳細ページを見ることができない
　→コントローラーで商品詳細ページは除く形で、設定変更しました。
○ 出品されている商品のページから購入をクリックするとエラー画面になる
　→カテゴリの記述式に問題がありました。if分岐を追加して修正しました。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
